Add method to delete allocation by username
webrtc-rs/turn pull request #16
Opened 2022-08-05 08:47 UTC by logist322

## Synopsis

In some cases it is necessary to manage the TURN server straight from the media server.

## Solution

The `Command` protocol has been added to communicate by channels between the `Server`'s public methods and the threads spawned in the `reed_loop` method. Now there is only `DeleteAllocation` command, but this protocol can become wider when it is needed to implement another public API.

2022-08-16 14:22 UTC, logist322 commented
@tyranron for review.

2022-08-17 08:52 UTC, tyranron requested changes

2022-08-17 08:52 UTC, tyranron commented on src/allocation/allocation_manager.rs
> +    pub async fn delete_allocations_by_username(&self, name: String) {
@logist322 why not `name: &str`?

2022-08-18 16:47 UTC, tyranron approved these changes

2022-08-18 16:47 UTC, tyranron commented on src/allocation/mod.rs
> +        self.closed.store(true, Ordering::Release);
@logist322 with atomics you do have atomicity regarding the single operation, but you don't have atomicity with two separate operations. So, loading and then storing separately is not atomic and will race. That's why there are compare-and-swap operations on atomics.

2022-08-19 11:35 UTC, logist322 commented
@rainliu request for review.

2022-08-23 12:35 UTC, k0nserv commented
We have migrated this crate to the monorepo([webrtc-rs/webrtc](https://github.com/webrtc-rs/webrtc/)) please re-open this pull request over there.

2022-08-23 12:35 UTC, closed without merging